title: Karolay De La Cruz # your name (or website title) here
logo: #"/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  MSc in Automation and Robotics
  <br><br>
  An avid learner with experience in the use of AI for robotic platforms.
  Interest in Data Science and its use in problem-solving.
  <br><br>
  <a href="https://www.linkedin.com/in/karolay-de-la-cruz/" class="social-icon si-rounded si-small si-linkedin">
    <i class="fa fa-linkedin" aria-hidden="true">
  </a>
  
theme: jekyll-theme-minimal
google_analytics:  # your Google Analytics tracking ID here
