title: Karolay De La Cruz # your name (or website title) here
prof: MSc Automation and Robotic
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  A passionate learner with expertise in applying AI to robotics. I also leverage data science techniques for 
  innovative problem-solving.
  <br><br>
theme: jekyll-theme-minimal
