title: Karolay De La Cruz # your name (or website title) here
logo: # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  MSc Automation and Robotics
  <br><br>
  An avid learner with experience in the use of AI for robotic platforms.
  Interest in Data Science and its use in problem-solving.
  <br><br>
  <a href=""></a>
theme: jekyll-theme-minimal
google_analytics:  # your Google Analytics tracking ID here
