title: Dina De La Cruz # your name (or website title) here
prof: MSc Automation and Robotic
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  My expertise lies in implementing AI for robotics, supported by strong skills in data science and software development to drive innovative problem-solving.
  <br><br>
theme: jekyll-theme-minimal
