title: Karolay De La Cruz
description: >
  Tutorials, projects and more.
permalink: ':title/'
#vbaseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "https://karolaydelacruz.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Karolay De La Cruz # add your name
author-img: portfolio.jpg # add your photo
about-author: Automation and Robotics Engineer.
  My experience focuses on the implementation of AI for robotic platforms.
  I also have a great interest in Data Science and its use in solving business problems. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: KarolayDeLaCruz # add your Github handle
social-linkedin: karolay-de-la-cruz # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: miss-delacruz # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
