title: Karolay De La Cruz # your name (or website title) here
prof: MSc Automation and Robotic
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  An avid learner with experience in the use of AI for robotic platforms.
  Interest in Data Science and its use in problem-solving.
  <br><br>
theme: jekyll-theme-minimal
